cask_args appdir: "/Applications"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-drivers"

brew "fish"
brew "git"
brew "neovim"
brew "tmux"
brew "anyenv"
brew "mas"
brew "exa"
brew "peco"
brew "ghq"
brew "curl"
brew "wget"
brew "reattach-to-user-namespace"
brew "tree-sitter"
brew "ripgrep"
brew "ninja"
brew "lua-language-server"
brew "pnpm"

#cask "google-chrome"
cask "firefox"
#cask "slack"
cask "zoom"
cask "iterm2"
cask "webstorm"
cask "visual-studio-code"
cask "docker"
cask "postman"
cask "karabiner-elements"
cask "clipy"
cask "appcleaner"

tap "homebrew/cask-fonts"
cask "font-hack-nerd-font"
