cask_args appdir: "/Applications"

brew "fish"
brew "git"
brew "gh"
brew "lazygit"
brew "neovim"
brew "tmux"
brew "anyenv"
brew "mas"
brew "eza"
brew "peco"
brew "ghq"
brew "curl"
brew "wget"
brew "tree-sitter"
brew "ripgrep"
brew "fd"
brew "chafa"

cask "google-chrome"
cask "firefox"
cask "slack"
cask "zoom"
cask "iterm2"
cask "webstorm"
cask "visual-studio-code"
cask "docker-desktop"
cask "postman"
cask "karabiner-elements"
cask "clipy"
cask "appcleaner"
cask "philips-hue-sync"
cask "kindle"
cask "astro-command-center"

mas "LINE", id: 539883307
mas "The Unarchiver", id: 425424353

cask "font-hack-nerd-font"
