gui:
  nerdFontsVersion: "3" # show nerd font icons
keybinding:
  universal:
    prevBlock: "<c-p>" # goto the previous block / panel
    nextBlock: "<c-n>" # goto the next block / panel
customCommands:
  - key: "C"
    command: "git cz"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
git:
  parseEmoji: true
